[chore] [exporterhelper] Remove flaky redundant test
The test is checking the behavior that is available for the user. Zero consumers nor zero queue size are not allowed.

With the given input The test is running in a race condition and fails when Offer is called before `Consume`

```
--- FAIL: TestZeroSizeWithConsumers (0.00s)
    bounded_memory_queue_test.go:242:
        	Error Trace:	/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/bounded_memory_queue_test.go:242
        	Error:      	Received unexpected error:
        	            	sending queue is full
        	Test:       	TestZeroSizeWithConsumers
FAIL
```