[chore] Fix flaky test TestPersistentQueue_FullCapacity (#8980)
Another fix for the flaky test `TestPersistentQueue_FullCapacity`. We
need to make sure that the first item is consumed from the queue before
proceeding. Otherwise, it can occasionally fail with:

```
--- FAIL: TestPersistentQueue_FullCapacity (0.00s)
    persistent_queue_test.go:91:
        	Error Trace:	/home/runner/work/opentelemetry-collector/opentelemetry-collector/exporter/exporterhelper/internal/persistent_queue_test.go:91
        	Error:      	Received unexpected error:
        	            	sending queue is full
        	Test:       	TestPersistentQueue_FullCapacity
FAIL
```