Fix OTLP receiver Shutdown() bug
OTLP receiver had a bug due to which it could generate data after Shutdown()
was returned.

It was visible in TestShutdown, with the following symptoms (it was a racy bug):

=== RUN   TestShutdown
    otlp_test.go:871:
        	Error Trace:	otlp_test.go:871
        	Error:      	Not equal:
        	            	expected: 4
        	            	actual  : 5
        	Test:       	TestShutdown
    otlp_test.go:871:
        	Error Trace:	otlp_test.go:871
        	Error:      	Not equal:
        	            	expected: 6
        	            	actual  : 7
        	Test:       	TestShutdown
--- FAIL: TestShutdown (0.49s)

I added a Helper which allows to wait until all in-flight operations are complete
before the Shutdown() function returns.

The Helper can be used by other components too in the future.